/*
 * NIGHTFALL — procedural dread audio: an ambient drone that swells with
 * danger, a panic heartbeat, footsteps, and the shrine hum. Assets are
 * generated by tools/gen_audio.py; loaded and freed in main.c.
 */
#include "game.h"

Mix_Chunk *snd_ambient, *snd_heart, *snd_scare, *snd_pickup, *snd_step, *snd_whisper;
Mix_Chunk *snd_roar, *snd_growl, *snd_creak, *snd_shrine;
double heart_timer = 0.0, step_timer = 0.0;

/* Master volume: available since SDL_mixer 2.6. On older libs (some distros)
 * we simply skip it so the build stays portable — the slider then no-ops. */
void apply_master_volume(void) {
#if (SDL_MIXER_MAJOR_VERSION > 2) || (SDL_MIXER_MAJOR_VERSION == 2 && SDL_MIXER_MINOR_VERSION >= 6)
    Mix_MasterVolume(master_vol);
#endif
}
void update_audio(double dt, int moving) {
    double d = sqrt((posX - monX) * (posX - monX) + (posY - monY) * (posY - monY));
    double target = d < 9 ? (1.0 - d / 9.0) : 0.0;
    tension += (target - tension) * fmin(1.0, dt * 3);
    Mix_Volume(0, (int)(50 + 60 * tension));
    if (game_state == ST_PLAY && tension > 0.1) {
        double bpm = 55 + tension * 115;
        heart_timer -= dt;
        if (heart_timer <= 0) {
            Mix_VolumeChunk(snd_heart, (int)(30 + 98 * tension));
            Mix_PlayChannel(1, snd_heart, 0); heart_timer = 60.0 / bpm;
        }
    }
    if (moving && game_state == ST_PLAY) {
        step_timer -= dt;
        if (step_timer <= 0) { Mix_VolumeChunk(snd_step, 60); Mix_PlayChannel(2, snd_step, 0); step_timer = 0.42; }
    }
    /* shrine hum: a soft choral drone that swells as you near an unopened chest */
    if (snd_shrine) {
        double nd = 1e9;
        if (game_state == ST_PLAY)
            for (int i = 0; i < num_keys; i++)
                if (keys[i].active) {
                    double dx = posX - keys[i].x, dy = posY - keys[i].y, dk = sqrt(dx * dx + dy * dy);
                    if (dk < nd) nd = dk;
                }
        int vol = (nd < 6.5) ? (int)(58 * (1.0 - nd / 6.5)) : 0;
        if (vol > 0 && !Mix_Playing(CH_SHRINE)) Mix_PlayChannel(CH_SHRINE, snd_shrine, -1);
        Mix_Volume(CH_SHRINE, vol);
    }
}
