/*
 * NIGHTFALL — procedural dread audio: an ambient drone that swells with
 * danger, a panic heartbeat, footsteps, and the shrine hum. Assets are
 * generated by tools/gen_audio.py; loaded and freed in main.c.
 */
#include "game.h"

Mix_Chunk *snd_ambient, *snd_heart, *snd_scare, *snd_pickup, *snd_step, *snd_whisper;
Mix_Chunk *snd_roar, *snd_growl, *snd_creak, *snd_shrine, *snd_thud, *snd_door;
double heart_timer = 0.0, step_timer = 0.0;

/* Master volume: available since SDL_mixer 2.6. On older libs (some distros)
 * we simply skip it so the build stays portable — the slider then no-ops. */
void apply_master_volume(void) {
#if (SDL_MIXER_MAJOR_VERSION > 2) || (SDL_MIXER_MAJOR_VERSION == 2 && SDL_MIXER_MINOR_VERSION >= 6)
    Mix_MasterVolume(master_vol);
#endif
}

/* Pan a channel toward a world point relative to the player's facing, using
 * SDL_mixer's built-in position effect (a cheap per-channel stereo-pan post
 * filter, not a per-frame cost). Distance is left at 0 -- loudness by
 * proximity is already hand-tuned per sound via Mix_VolumeChunk, so this
 * only adds *direction*, it doesn't re-attenuate on top of that.          */
void play_positional(int channel, double srcX, double srcY) {
    double dx = srcX - posX, dy = srcY - posY;
    double fwd = dx * cos(yaw) + dy * sin(yaw);
    double rgt = -dx * sin(yaw) + dy * cos(yaw);
    double deg = atan2(rgt, fwd) * (180.0 / 3.14159265);   /* 0 ahead, +right */
    if (deg < 0) deg += 360.0;
    Mix_SetPosition(channel, (Sint16)deg, 0);
}
void update_audio(double dt, int moving) {
    double d = sqrt((posX - monX) * (posX - monX) + (posY - monY) * (posY - monY));
    double target = d < 9 ? (1.0 - d / 9.0) : 0.0;
    tension += (target - tension) * fmin(1.0, dt * 3);
    Mix_Volume(0, (int)(50 + 60 * tension));
    if (game_state == ST_PLAY && tension > 0.1) {
        double bpm = 55 + tension * 115;
        heart_timer -= dt;
        if (heart_timer <= 0) {
            Mix_VolumeChunk(snd_heart, (int)(30 + 98 * tension));
            Mix_PlayChannel(1, snd_heart, 0); heart_timer = 60.0 / bpm;
        }
    }
    if (moving && game_state == ST_PLAY) {
        step_timer -= dt;
        if (step_timer <= 0) { Mix_VolumeChunk(snd_step, 60); Mix_PlayChannel(2, snd_step, 0);
            Mix_SetPosition(2, 0, 0);                  /* your own feet: dead centre */
            step_timer = 0.42; }
    }
    /* shrine hum: a soft choral drone that swells as you near an unopened chest */
    if (snd_shrine) {
        double nd = 1e9; int nk = -1;
        if (game_state == ST_PLAY)
            for (int i = 0; i < num_keys; i++)
                if (keys[i].active) {
                    double dx = posX - keys[i].x, dy = posY - keys[i].y, dk = sqrt(dx * dx + dy * dy);
                    if (dk < nd) { nd = dk; nk = i; }
                }
        int vol = (nd < 6.5) ? (int)(58 * (1.0 - nd / 6.5)) : 0;
        if (vol > 0 && !Mix_Playing(CH_SHRINE)) Mix_PlayChannel(CH_SHRINE, snd_shrine, -1);
        Mix_Volume(CH_SHRINE, vol);
        if (vol > 0 && nk >= 0) play_positional(CH_SHRINE, keys[nk].x, keys[nk].y);
    }
}
