/*
 * NIGHTFALL — a first-person horror game for Linux.
 *
 * A pseudo-3D raycasting engine (Wolfenstein-style) rendered into a software
 * framebuffer, dressed as a pitch-black maze. You carry a failing flashlight.
 * Something is in here with you: The Stalker, a sprite that hunts you through
 * the corridors using a breadth-first flood-field. Find three keys, reach the
 * exit — and don't let it catch you, because when it does, it fills the screen.
 *
 * Audio (a dread drone, a heartbeat that races as it nears, and the scream)
 * is procedurally generated by tools/gen_audio.py — no binary assets required.
 *
 * Build:  make          (needs SDL2 + SDL2_mixer dev packages)
 * Run:    ./nightfall
 *
 * Controls:  W/A/S/D move   Mouse look   Shift run   E interact   Esc quit
 */

#include <SDL2/SDL.h>
#include <SDL2/SDL_mixer.h>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

/* ------------------------------------------------------------------ config */
#define SCREEN_W 960
#define SCREEN_H 540
#define TEX      64

#define MW 21          /* maze width  (odd) */
#define MH 15          /* maze height (odd) */
#define NUM_KEYS 3

#define PLAYER_WALK 3.1
#define PLAYER_RUN  4.7
#define MONSTER_SPD 2.15
#define CATCH_DIST  0.55
#define PICKUP_DIST 0.55

#define CONE     0.62   /* flashlight cone half-width in camera units */
#define AMBIENT  0.045  /* how dark the world is outside the beam      */
#define FOG_K    0.10   /* distance darkening                          */

/* ------------------------------------------------------------------- state */
enum { ST_TITLE, ST_PLAY, ST_CAUGHT, ST_WIN };

static char  map[MH][MW + 1];
static double posX, posY, dirX, dirY, planeX, planeY;
static double monX, monY;
static int    gdist[MH][MW];            /* BFS flood field from the player   */

typedef struct { double x, y; int active; } Key;
static Key   keys[NUM_KEYS];
static int   keys_left;
static double exitX, exitY;

static int    game_state = ST_TITLE;
static double state_time = 0.0;         /* seconds spent in current state     */
static double tension    = 0.0;         /* 0..1 proximity of the Stalker      */
static double flicker    = 1.0;

static uint32_t fb[SCREEN_W * SCREEN_H];
static double   zbuf[SCREEN_W];

/* textures: 0 wall, 1 floor, 2 ceiling */
static uint32_t tex[3][TEX * TEX];

/* sprites: monster / key / exit share a small procedural texture set.
 * flags: 0 = transparent, 1 = shaded normally, 2 = self-lit glow.          */
static uint32_t spr_col[3][TEX * TEX];
static uint8_t  spr_flg[3][TEX * TEX];

/* audio */
static Mix_Chunk *snd_ambient, *snd_heart, *snd_scare, *snd_pickup, *snd_step;
static double heart_timer = 0.0, step_timer = 0.0;
static int    scare_played = 0;

/* --------------------------------------------------------------- utilities */
static inline uint32_t pack(int r, int g, int b) {
    if (r < 0) r = 0;
    if (r > 255) r = 255;
    if (g < 0) g = 0;
    if (g > 255) g = 255;
    if (b < 0) b = 0;
    if (b > 255) b = 255;
    return 0xFF000000u | (r << 16) | (g << 8) | b;
}
static inline uint32_t shade(uint32_t c, double f) {
    int r = (int)(((c >> 16) & 255) * f);
    int g = (int)(((c >> 8) & 255) * f);
    int b = (int)((c & 255) * f);
    return pack(r, g, b);
}
static double frand(void) { return rand() / (double)RAND_MAX; }

/* flashlight + fog brightness for a screen column at camera x, distance d */
static double light(double camx, double d) {
    double cone = 1.0 - (camx * camx) / (CONE * CONE);
    if (cone < 0) cone = 0;
    cone *= cone;
    double fog = 1.0 / (1.0 + d * d * FOG_K);
    double b = AMBIENT + (1.0 - AMBIENT) * cone;
    b *= (0.12 + 0.88 * fog);
    return b * flicker;
}

/* ----------------------------------------------------------- 5x7 pixel font */
static const unsigned char FONT[][7] = {
    {0x0E,0x11,0x11,0x1F,0x11,0x11,0x11}, /* A */
    {0x1E,0x11,0x11,0x1E,0x11,0x11,0x1E}, /* B */
    {0x0E,0x11,0x10,0x10,0x10,0x11,0x0E}, /* C */
    {0x1E,0x11,0x11,0x11,0x11,0x11,0x1E}, /* D */
    {0x1F,0x10,0x10,0x1E,0x10,0x10,0x1F}, /* E */
    {0x1F,0x10,0x10,0x1E,0x10,0x10,0x10}, /* F */
    {0x0E,0x11,0x10,0x17,0x11,0x11,0x0F}, /* G */
    {0x11,0x11,0x11,0x1F,0x11,0x11,0x11}, /* H */
    {0x0E,0x04,0x04,0x04,0x04,0x04,0x0E}, /* I */
    {0x07,0x02,0x02,0x02,0x02,0x12,0x0C}, /* J */
    {0x11,0x12,0x14,0x18,0x14,0x12,0x11}, /* K */
    {0x10,0x10,0x10,0x10,0x10,0x10,0x1F}, /* L */
    {0x11,0x1B,0x15,0x15,0x11,0x11,0x11}, /* M */
    {0x11,0x11,0x19,0x15,0x13,0x11,0x11}, /* N */
    {0x0E,0x11,0x11,0x11,0x11,0x11,0x0E}, /* O */
    {0x1E,0x11,0x11,0x1E,0x10,0x10,0x10}, /* P */
    {0x0E,0x11,0x11,0x11,0x15,0x12,0x0D}, /* Q */
    {0x1E,0x11,0x11,0x1E,0x14,0x12,0x11}, /* R */
    {0x0F,0x10,0x10,0x0E,0x01,0x01,0x1E}, /* S */
    {0x1F,0x04,0x04,0x04,0x04,0x04,0x04}, /* T */
    {0x11,0x11,0x11,0x11,0x11,0x11,0x0E}, /* U */
    {0x11,0x11,0x11,0x11,0x11,0x0A,0x04}, /* V */
    {0x11,0x11,0x11,0x15,0x15,0x1B,0x11}, /* W */
    {0x11,0x11,0x0A,0x04,0x0A,0x11,0x11}, /* X */
    {0x11,0x11,0x0A,0x04,0x04,0x04,0x04}, /* Y */
    {0x1F,0x01,0x02,0x04,0x08,0x10,0x1F}, /* Z */
    {0x0E,0x11,0x13,0x15,0x19,0x11,0x0E}, /* 0 */
    {0x04,0x0C,0x04,0x04,0x04,0x04,0x0E}, /* 1 */
    {0x0E,0x11,0x01,0x02,0x04,0x08,0x1F}, /* 2 */
    {0x1F,0x02,0x04,0x02,0x01,0x11,0x0E}, /* 3 */
    {0x02,0x06,0x0A,0x12,0x1F,0x02,0x02}, /* 4 */
    {0x1F,0x10,0x1E,0x01,0x01,0x11,0x0E}, /* 5 */
    {0x06,0x08,0x10,0x1E,0x11,0x11,0x0E}, /* 6 */
    {0x1F,0x01,0x02,0x04,0x08,0x08,0x08}, /* 7 */
    {0x0E,0x11,0x11,0x0E,0x11,0x11,0x0E}, /* 8 */
    {0x0E,0x11,0x11,0x0F,0x01,0x02,0x0C}, /* 9 */
    {0x00,0x00,0x00,0x00,0x00,0x00,0x00}, /* space */
    {0x01,0x02,0x02,0x04,0x08,0x08,0x10}, /* /  */
    {0x00,0x04,0x04,0x00,0x00,0x04,0x04}, /* :  */
    {0x04,0x04,0x04,0x04,0x04,0x00,0x04}, /* !  */
    {0x00,0x00,0x00,0x00,0x00,0x0C,0x0C}, /* .  */
    {0x00,0x00,0x00,0x1F,0x00,0x00,0x00}, /* -  */
};
static int glyph(char c) {
    if (c >= 'a' && c <= 'z') c -= 32;
    if (c >= 'A' && c <= 'Z') return c - 'A';
    if (c >= '0' && c <= '9') return 26 + (c - '0');
    switch (c) {
        case ' ': return 36; case '/': return 37; case ':': return 38;
        case '!': return 39; case '.': return 40; case '-': return 41;
    }
    return 36;
}
static void draw_char(int x, int y, int s, char c, uint32_t col) {
    const unsigned char *g = FONT[glyph(c)];
    for (int row = 0; row < 7; row++)
        for (int cx = 0; cx < 5; cx++)
            if (g[row] & (1 << (4 - cx)))
                for (int py = 0; py < s; py++)
                    for (int px = 0; px < s; px++) {
                        int X = x + cx * s + px, Y = y + row * s + py;
                        if (X >= 0 && X < SCREEN_W && Y >= 0 && Y < SCREEN_H)
                            fb[Y * SCREEN_W + X] = col;
                    }
}
static void draw_text(int x, int y, int s, const char *t, uint32_t col) {
    for (; *t; t++) { draw_char(x, y, s, *t, col); x += 6 * s; }
}
static void draw_text_c(int y, int s, const char *t, uint32_t col) {
    int w = (int)strlen(t) * 6 * s;
    draw_text((SCREEN_W - w) / 2, y, s, t, col);
}

/* ------------------------------------------------------------ texture build */
static void build_textures(void) {
    for (int y = 0; y < TEX; y++)
        for (int x = 0; x < TEX; x++) {
            int i = y * TEX + x;
            /* wall: dark blood-brick */
            int brick_h = 16, brick_w = 32;
            int row = y / brick_h;
            int ox = (row & 1) ? brick_w / 2 : 0;
            int mortar = ((x + ox) % brick_w < 2) || (y % brick_h < 2);
            int base = 46 + (int)(frand() * 16);
            if (mortar) tex[0][i] = pack(base / 3, base / 4, base / 4);
            else {
                int r = base, g = base * 0.42, b = base * 0.38;
                if (frand() < 0.05) { r += 40; }         /* stains */
                tex[0][i] = pack(r, g, b);
            }
            /* floor: cold wet stone */
            int f = 30 + (int)(frand() * 14);
            int crack = ((x * 7 + y * 3) % 29 < 2);
            tex[1][i] = crack ? pack(8, 9, 10) : pack(f, f, f + 4);
            /* ceiling: near black */
            int c = 10 + (int)(frand() * 6);
            tex[2][i] = pack(c, c, c + 2);
        }
}

static void put_sprite_px(int t, int x, int y, uint32_t col, uint8_t flg) {
    if (x < 0 || x >= TEX || y < 0 || y >= TEX) return;
    spr_col[t][y * TEX + x] = col;
    spr_flg[t][y * TEX + x] = flg;
}
static void build_sprites(void) {
    memset(spr_flg, 0, sizeof(spr_flg));
    /* 0: THE STALKER — a hunched, hooded figure with burning eyes */
    for (int y = 0; y < TEX; y++)
        for (int x = 0; x < TEX; x++) {
            double nx = x - 32.0;
            int inside = 0;
            if (y < 24) {                                  /* hooded head */
                double hy = y - 15.0;
                if (nx * nx / (11 * 11.0) + hy * hy / (13 * 13.0) < 1.0) inside = 1;
            }
            double half = 8 + (y - 22) * 0.42;             /* body flares out */
            if (y >= 22 && fabs(nx) < half) inside = 1;
            if (inside) {
                int v = 8 + (int)(frand() * 8);
                put_sprite_px(0, x, y, pack(v, v, v + 2), 1);
            }
        }
    for (int y = 10; y <= 16; y++)                         /* two red eyes */
        for (int x = 0; x < TEX; x++) {
            double d1 = (x - 25.0) * (x - 25.0) + (y - 13.0) * (y - 13.0);
            double d2 = (x - 39.0) * (x - 39.0) + (y - 13.0) * (y - 13.0);
            if (d1 < 5 || d2 < 5) put_sprite_px(0, x, y, pack(255, 40, 30), 2);
            else if (d1 < 12 || d2 < 12) put_sprite_px(0, x, y, pack(120, 10, 8), 2);
        }
    /* 1: KEY — a glowing amber sigil */
    for (int y = 0; y < TEX; y++)
        for (int x = 0; x < TEX; x++) {
            double dx = x - 32.0, dy = y - 26.0;
            double r = sqrt(dx * dx + dy * dy);
            if (r < 8) put_sprite_px(1, x, y, pack(255, 210, 30), 2);
            else if (r < 11) put_sprite_px(1, x, y, pack(150, 110, 15), 2);
            if (x >= 30 && x <= 33 && y >= 30 && y <= 46)
                put_sprite_px(1, x, y, pack(255, 210, 30), 2);
            if (y >= 40 && y <= 46 && x >= 33 && x <= 39 && (y % 4 < 2))
                put_sprite_px(1, x, y, pack(255, 210, 30), 2);
        }
    /* 2: EXIT — a cold green doorway of light */
    for (int y = 0; y < TEX; y++)
        for (int x = 0; x < TEX; x++) {
            int frame = (x >= 16 && x <= 47 && y >= 6 && y <= 60);
            int edge = frame && (x <= 19 || x >= 44 || y <= 9);
            int inner = (x >= 22 && x <= 41 && y >= 12 && y <= 60);
            if (edge) put_sprite_px(2, x, y, pack(60, 255, 130), 2);
            else if (inner) {
                int g = 40 + (60 - y) * 2;
                put_sprite_px(2, x, y, pack(10, g < 0 ? 0 : g, 40), 2);
            }
        }
}

/* --------------------------------------------------------------- maze build */
static void carve(void) {
    for (int y = 0; y < MH; y++) { for (int x = 0; x < MW; x++) map[y][x] = '#'; map[y][MW] = 0; }
    int sx[MW * MH], sy[MW * MH], sp = 0;
    int cx = 1, cy = 1;
    map[cy][cx] = '.';
    sx[sp] = cx; sy[sp] = cy; sp++;
    int dx[] = {0, 0, -2, 2}, dy[] = {-2, 2, 0, 0};
    while (sp > 0) {
        cx = sx[sp - 1]; cy = sy[sp - 1];
        int o[4] = {0, 1, 2, 3};
        for (int i = 3; i > 0; i--) { int j = rand() % (i + 1), t = o[i]; o[i] = o[j]; o[j] = t; }
        int moved = 0;
        for (int k = 0; k < 4; k++) {
            int nx = cx + dx[o[k]], ny = cy + dy[o[k]];
            if (nx > 0 && nx < MW - 1 && ny > 0 && ny < MH - 1 && map[ny][nx] == '#') {
                map[cy + dy[o[k]] / 2][cx + dx[o[k]] / 2] = '.';
                map[ny][nx] = '.';
                sx[sp] = nx; sy[sp] = ny; sp++;
                moved = 1; break;
            }
        }
        if (!moved) sp--;
    }
    /* punch a few extra openings so it loops — nastier to escape */
    for (int i = 0; i < MW * MH / 12; i++) {
        int x = 1 + rand() % (MW - 2), y = 1 + rand() % (MH - 2);
        if (map[y][x] == '#') map[y][x] = '.';
    }
}
static int is_open(int x, int y) {
    return x >= 0 && x < MW && y >= 0 && y < MH && map[y][x] != '#';
}

/* BFS flood field: gdist = walking distance from the player's cell. */
static void flood_from_player(void) {
    for (int y = 0; y < MH; y++) for (int x = 0; x < MW; x++) gdist[y][x] = 1 << 20;
    int qx[MW * MH], qy[MW * MH], h = 0, t = 0;
    int px = (int)posX, py = (int)posY;
    gdist[py][px] = 0; qx[t] = px; qy[t] = py; t++;
    int dx[] = {0, 0, -1, 1}, dy[] = {-1, 1, 0, 0};
    while (h < t) {
        int x = qx[h], y = qy[h]; h++;
        for (int k = 0; k < 4; k++) {
            int nx = x + dx[k], ny = y + dy[k];
            if (is_open(nx, ny) && gdist[ny][nx] > gdist[y][x] + 1) {
                gdist[ny][nx] = gdist[y][x] + 1;
                qx[t] = nx; qy[t] = ny; t++;
            }
        }
    }
}

static void reset_level(void) {
    carve();
    posX = 1.5; posY = 1.5;
    dirX = 1;   dirY = 0;
    planeX = 0; planeY = 0.66;

    /* exit at the far corner */
    exitX = MW - 2 + 0.5; exitY = MH - 2 + 0.5;
    map[MH - 2][MW - 2] = '.';

    /* keys on open cells, far from the start and from each other */
    keys_left = NUM_KEYS;
    for (int i = 0; i < NUM_KEYS; i++) {
        for (;;) {
            int x = 1 + rand() % (MW - 2), y = 1 + rand() % (MH - 2);
            if (!is_open(x, y)) continue;
            if (abs(x - 1) + abs(y - 1) < 6) continue;
            int ok = 1;
            for (int j = 0; j < i; j++)
                if (fabs(keys[j].x - (x + 0.5)) + fabs(keys[j].y - (y + 0.5)) < 4) ok = 0;
            if (!ok) continue;
            keys[i].x = x + 0.5; keys[i].y = y + 0.5; keys[i].active = 1;
            break;
        }
    }
    /* the Stalker starts across the maze from you */
    for (;;) {
        int x = 1 + rand() % (MW - 2), y = 1 + rand() % (MH - 2);
        if (is_open(x, y) && abs(x - 1) + abs(y - 1) > MW / 2) {
            monX = x + 0.5; monY = y + 0.5; break;
        }
    }
    tension = 0; flicker = 1; scare_played = 0;
    heart_timer = step_timer = 0;
    flood_from_player();
}

/* ------------------------------------------------------------------ physics */
static void try_move(double nx, double ny, double radius) {
    if (is_open((int)(nx + (nx > posX ? radius : -radius)), (int)posY)) posX = nx;
    if (is_open((int)posX, (int)(ny + (ny > posY ? radius : -radius)))) posY = ny;
}
static void rotate(double a) {
    double od = dirX;
    dirX = dirX * cos(a) - dirY * sin(a);
    dirY = od   * sin(a) + dirY * cos(a);
    double op = planeX;
    planeX = planeX * cos(a) - planeY * sin(a);
    planeY = op     * sin(a) + planeY * cos(a);
}

static void update_monster(double dt) {
    int cx = (int)monX, cy = (int)monY;
    int best = gdist[cy][cx], bx = cx, by = cy;
    int dx[] = {0, 0, -1, 1}, dy[] = {-1, 1, 0, 0};
    for (int k = 0; k < 4; k++) {
        int nx = cx + dx[k], ny = cy + dy[k];
        if (is_open(nx, ny) && gdist[ny][nx] < best) { best = gdist[ny][nx]; bx = nx; by = ny; }
    }
    double tx = bx + 0.5, ty = by + 0.5;
    double vx = tx - monX, vy = ty - monY;
    double len = sqrt(vx * vx + vy * vy);
    if (len > 1e-4) {
        double step = MONSTER_SPD * dt;
        if (step > len) step = len;
        monX += vx / len * step;
        monY += vy / len * step;
    }
}

/* --------------------------------------------------------------- rendering */
static void render_world(void) {
    /* floor & ceiling cast */
    for (int y = SCREEN_H / 2 + 1; y < SCREEN_H; y++) {
        double rowDist = (0.5 * SCREEN_H) / (y - SCREEN_H / 2);
        double rdxL = dirX - planeX, rdyL = dirY - planeY;
        double rdxR = dirX + planeX, rdyR = dirY + planeY;
        double fx = posX + rowDist * rdxL, fy = posY + rowDist * rdyL;
        double sx = rowDist * (rdxR - rdxL) / SCREEN_W;
        double sy = rowDist * (rdyR - rdyL) / SCREEN_W;
        for (int x = 0; x < SCREEN_W; x++) {
            int tx = ((int)(TEX * fx)) & (TEX - 1);
            int ty = ((int)(TEX * fy)) & (TEX - 1);
            double camx = 2.0 * x / SCREEN_W - 1.0;
            double b = light(camx, rowDist);
            fb[y * SCREEN_W + x] = shade(tex[1][ty * TEX + tx], b);
            fb[(SCREEN_H - y) * SCREEN_W + x] = shade(tex[2][ty * TEX + tx], b * 0.7);
            fx += sx; fy += sy;
        }
    }
    /* walls via DDA */
    for (int x = 0; x < SCREEN_W; x++) {
        double camx = 2.0 * x / SCREEN_W - 1.0;
        double rdx = dirX + planeX * camx, rdy = dirY + planeY * camx;
        int mapX = (int)posX, mapY = (int)posY;
        double ddX = fabs(1 / rdx), ddY = fabs(1 / rdy);
        int stepX, stepY, side = 0;
        double sdX, sdY;
        if (rdx < 0) { stepX = -1; sdX = (posX - mapX) * ddX; }
        else         { stepX = 1;  sdX = (mapX + 1 - posX) * ddX; }
        if (rdy < 0) { stepY = -1; sdY = (posY - mapY) * ddY; }
        else         { stepY = 1;  sdY = (mapY + 1 - posY) * ddY; }
        int hit = 0;
        while (!hit) {
            if (sdX < sdY) { sdX += ddX; mapX += stepX; side = 0; }
            else           { sdY += ddY; mapY += stepY; side = 1; }
            if (!is_open(mapX, mapY)) hit = 1;
        }
        double perp = side ? (sdY - ddY) : (sdX - ddX);
        if (perp < 0.02) perp = 0.02;
        zbuf[x] = perp;
        int h = (int)(SCREEN_H / perp);
        int y0 = -h / 2 + SCREEN_H / 2; if (y0 < 0) y0 = 0;
        int y1 =  h / 2 + SCREEN_H / 2; if (y1 >= SCREEN_H) y1 = SCREEN_H - 1;
        double wallX = side ? posX + perp * rdx : posY + perp * rdy;
        wallX -= floor(wallX);
        int texX = (int)(wallX * TEX);
        if ((!side && rdx > 0) || (side && rdy < 0)) texX = TEX - texX - 1;
        double b = light(camx, perp) * (side ? 0.72 : 1.0);
        for (int y = y0; y <= y1; y++) {
            int texY = ((y * 2 - SCREEN_H + h) * TEX) / (2 * h);
            if (texY < 0) texY = 0;
            if (texY >= TEX) texY = TEX - 1;
            fb[y * SCREEN_W + x] = shade(tex[0][texY * TEX + texX], b);
        }
    }
}

typedef struct { double dist; double x, y; int type; } Sprite;
static void render_sprites(void) {
    Sprite s[NUM_KEYS + 2];
    int n = 0;
    if (game_state == ST_PLAY) { s[n].x = monX; s[n].y = monY; s[n].type = 0; n++; }
    for (int i = 0; i < NUM_KEYS; i++)
        if (keys[i].active) { s[n].x = keys[i].x; s[n].y = keys[i].y; s[n].type = 1; n++; }
    if (keys_left == 0) { s[n].x = exitX; s[n].y = exitY; s[n].type = 2; n++; }
    for (int i = 0; i < n; i++)
        s[i].dist = (posX - s[i].x) * (posX - s[i].x) + (posY - s[i].y) * (posY - s[i].y);
    for (int i = 0; i < n; i++)                     /* far to near */
        for (int j = i + 1; j < n; j++)
            if (s[j].dist > s[i].dist) { Sprite t = s[i]; s[i] = s[j]; s[j] = t; }

    for (int i = 0; i < n; i++) {
        double spx = s[i].x - posX, spy = s[i].y - posY;
        double inv = 1.0 / (planeX * dirY - dirX * planeY);
        double tx = inv * (dirY * spx - dirX * spy);
        double ty = inv * (-planeY * spx + planeX * spy);
        if (ty <= 0.05) continue;
        int screenX = (int)((SCREEN_W / 2) * (1 + tx / ty));
        double scale = (s[i].type == 0) ? 1.15 : 0.6;   /* monster looms larger */
        int h = abs((int)(SCREEN_H / ty * scale));
        int vOff = (int)((s[i].type == 0 ? 0.0 : 0.35) * SCREEN_H / ty);
        int y0 = -h / 2 + SCREEN_H / 2 + vOff;
        int y1 =  h / 2 + SCREEN_H / 2 + vOff;
        int w = h;
        double camx = 2.0 * screenX / SCREEN_W - 1.0;
        double b = light(camx, ty);
        for (int stripe = screenX - w / 2; stripe < screenX + w / 2; stripe++) {
            if (stripe < 0 || stripe >= SCREEN_W) continue;
            if (ty >= zbuf[stripe]) continue;
            int texX = (stripe - (screenX - w / 2)) * TEX / w;
            if (texX < 0 || texX >= TEX) continue;
            for (int y = y0; y < y1; y++) {
                if (y < 0 || y >= SCREEN_H) continue;
                int texY = (y - y0) * TEX / h;
                if (texY < 0 || texY >= TEX) continue;
                uint8_t f = spr_flg[s[i].type][texY * TEX + texX];
                if (!f) continue;
                uint32_t c = spr_col[s[i].type][texY * TEX + texX];
                /* glow texels stay visible in the dark; bodies obey the light */
                fb[y * SCREEN_W + stripe] = (f == 2) ? shade(c, 0.35 + 0.65 * b)
                                                     : shade(c, b);
            }
        }
    }
}

static void draw_vignette(void) {
    for (int y = 0; y < SCREEN_H; y++)
        for (int x = 0; x < SCREEN_W; x++) {
            double dx = (x - SCREEN_W / 2.0) / (SCREEN_W / 2.0);
            double dy = (y - SCREEN_H / 2.0) / (SCREEN_H / 2.0);
            double r = dx * dx + dy * dy;
            double v = 1.0 - 0.85 * (r > 1 ? 1 : r) * (r > 1 ? 1 : r);
            if (v < 1.0) fb[y * SCREEN_W + x] = shade(fb[y * SCREEN_W + x], v);
        }
}

/* the full-screen face — shown the instant it catches you */
static void draw_jumpscare(void) {
    double t = state_time;
    double shake = (t < 1.2) ? 6 * sin(t * 90) : 0;
    for (int y = 0; y < SCREEN_H; y++)
        for (int x = 0; x < SCREEN_W; x++) {
            double nx = (x + shake - SCREEN_W / 2.0) / (SCREEN_H / 2.0);
            double ny = (y - SCREEN_H / 2.0) / (SCREEN_H / 2.0);
            uint32_t c = pack(4, 0, 0);
            double e1 = (nx + 0.42) * (nx + 0.42) + (ny + 0.15) * (ny + 0.15);
            double e2 = (nx - 0.42) * (nx - 0.42) + (ny + 0.15) * (ny + 0.15);
            if (e1 < 0.05 || e2 < 0.05) {
                double p = (e1 < 0.05 ? e1 : e2) / 0.05;
                c = pack(255 * (1 - p * 0.5), 40 * (1 - p), 20 * (1 - p));
                if ((e1 < 0.006) || (e2 < 0.006)) c = pack(10, 0, 0);   /* pupils */
            }
            /* jagged grin */
            if (ny > 0.28 && ny < 0.52 && fabs(nx) < 0.55) {
                double teeth = fabs(sin(nx * 26));
                if (ny < 0.30 + teeth * 0.16) c = pack(230, 225, 210);
            }
            double flash = (t < 0.6) ? (0.5 + 0.5 * sin(t * 60)) : 1.0;
            fb[y * SCREEN_W + x] = shade(c, flash);
        }
    if (t > 1.4) {
        draw_text_c(SCREEN_H / 2 - 40, 6, "IT FOUND YOU", pack(255, 30, 20));
        draw_text_c(SCREEN_H / 2 + 40, 3, "PRESS R TO GO BACK IN", pack(180, 180, 180));
    }
}

static void draw_title(void) {
    memset(fb, 0, sizeof(fb));
    /* faint drifting fog in the dark */
    for (int y = 0; y < SCREEN_H; y++)
        for (int x = 0; x < SCREEN_W; x++) {
            double v = 6 + 5 * sin(x * 0.01 + state_time) * sin(y * 0.017 - state_time * 0.7);
            fb[y * SCREEN_W + x] = pack((int)v, (int)v, (int)(v + 3));
        }
    uint32_t red = pack(190 + (int)(40 * sin(state_time * 3)), 20, 16);
    draw_text_c(140, 9, "NIGHTFALL", red);
    draw_text_c(250, 3, "SOMETHING IN THE DARK IS AWAKE.", pack(150, 150, 160));
    draw_text_c(285, 3, "FIND THREE KEYS. REACH THE EXIT.", pack(120, 120, 130));
    if ((int)(state_time * 2) % 2)
        draw_text_c(360, 4, "PRESS ENTER", pack(220, 220, 220));
    draw_text_c(SCREEN_H - 60, 2, "WASD MOVE   MOUSE LOOK   SHIFT RUN   ESC QUIT", pack(90, 90, 100));
}

static void draw_win(void) {
    for (int i = 0; i < SCREEN_W * SCREEN_H; i++) fb[i] = shade(fb[i], 0.25);
    draw_text_c(SCREEN_H / 2 - 50, 7, "YOU ESCAPED", pack(80, 255, 140));
    draw_text_c(SCREEN_H / 2 + 30, 3, "THE NIGHT LETS YOU GO. THIS TIME.", pack(180, 200, 190));
    draw_text_c(SCREEN_H / 2 + 70, 3, "PRESS R TO GO BACK IN", pack(150, 150, 150));
}

static void draw_hud(void) {
    char buf[32];
    snprintf(buf, sizeof(buf), "KEYS %d/%d", NUM_KEYS - keys_left, NUM_KEYS);
    draw_text(16, 16, 3, buf, pack(230, 210, 120));
    if (keys_left == 0)
        draw_text(16, 48, 3, "THE EXIT IS OPEN. RUN.", pack(90, 255, 150));
    /* proximity warning bleeds in as it nears */
    if (tension > 0.35) {
        int a = (int)(tension * 90);
        for (int y = 0; y < SCREEN_H; y++)
            for (int x = 0; x < SCREEN_W; x++) {
                double dx = (x - SCREEN_W / 2.0) / (SCREEN_W / 2.0);
                double dy = (y - SCREEN_H / 2.0) / (SCREEN_H / 2.0);
                if (dx * dx + dy * dy > 0.6) {
                    uint32_t c = fb[y * SCREEN_W + x];
                    int r = ((c >> 16) & 255) + a;
                    fb[y * SCREEN_W + x] = pack(r, (c >> 8) & 255, c & 255);
                }
            }
        if (tension > 0.75 && ((int)(state_time * 8) % 2))
            draw_text_c(90, 3, "IT IS CLOSE", pack(255, 40, 30));
    }
}

/* ------------------------------------------------------------------- audio */
static void update_audio(double dt, int moving) {
    double d = sqrt((posX - monX) * (posX - monX) + (posY - monY) * (posY - monY));
    double target = d < 9 ? (1.0 - d / 9.0) : 0.0;
    tension += (target - tension) * fmin(1.0, dt * 3);

    Mix_Volume(0, (int)(50 + 60 * tension));          /* ambient swells */

    if (game_state == ST_PLAY && tension > 0.1) {
        double bpm = 55 + tension * 115;              /* heart races */
        heart_timer -= dt;
        if (heart_timer <= 0) {
            Mix_VolumeChunk(snd_heart, (int)(30 + 98 * tension));
            Mix_PlayChannel(1, snd_heart, 0);
            heart_timer = 60.0 / bpm;
        }
    }
    if (moving && game_state == ST_PLAY) {
        step_timer -= dt;
        if (step_timer <= 0) {
            Mix_VolumeChunk(snd_step, 55);
            Mix_PlayChannel(2, snd_step, 0);
            step_timer = 0.42;
        }
    }
}

/* -------------------------------------------------------------------- main */
int main(int argc, char **argv) {
    (void)argc; (void)argv;
    srand((unsigned)time(NULL));

    if (SDL_Init(SDL_INIT_VIDEO | SDL_INIT_AUDIO) != 0) {
        fprintf(stderr, "SDL_Init: %s\n", SDL_GetError());
        return 1;
    }
    SDL_Window *win = SDL_CreateWindow("NIGHTFALL",
        SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED,
        SCREEN_W, SCREEN_H, SDL_WINDOW_SHOWN);
    SDL_Renderer *ren = SDL_CreateRenderer(win, -1, SDL_RENDERER_ACCELERATED | SDL_RENDERER_PRESENTVSYNC);
    SDL_Texture *screen = SDL_CreateTexture(ren, SDL_PIXELFORMAT_ARGB8888,
        SDL_TEXTUREACCESS_STREAMING, SCREEN_W, SCREEN_H);

    if (Mix_OpenAudio(44100, MIX_DEFAULT_FORMAT, 2, 1024) < 0)
        fprintf(stderr, "audio disabled: %s\n", Mix_GetError());
    Mix_AllocateChannels(8);
    snd_ambient = Mix_LoadWAV("assets/ambient.wav");
    snd_heart   = Mix_LoadWAV("assets/heartbeat.wav");
    snd_scare   = Mix_LoadWAV("assets/scare.wav");
    snd_pickup  = Mix_LoadWAV("assets/pickup.wav");
    snd_step    = Mix_LoadWAV("assets/step.wav");
    if (!snd_ambient)
        fprintf(stderr, "warning: assets not found — run 'make audio' first\n");
    if (snd_ambient) { Mix_Volume(0, 60); Mix_PlayChannel(0, snd_ambient, -1); }

    build_textures();
    build_sprites();
    reset_level();

    SDL_SetRelativeMouseMode(SDL_TRUE);
    if (getenv("NIGHTFALL_AUTOPLAY")) { game_state = ST_PLAY; state_time = 0; }
    double recalc = 0;
    Uint64 prev = SDL_GetPerformanceCounter();
    double freq = (double)SDL_GetPerformanceFrequency();
    int running = 1;

    while (running) {
        Uint64 now = SDL_GetPerformanceCounter();
        double dt = (now - prev) / freq;
        if (dt > 0.05) dt = 0.05;
        prev = now;
        state_time += dt;

        SDL_Event e;
        while (SDL_PollEvent(&e)) {
            if (e.type == SDL_QUIT) running = 0;
            if (e.type == SDL_KEYDOWN) {
                SDL_Keycode k = e.key.keysym.sym;
                if (k == SDLK_ESCAPE) running = 0;
                if (k == SDLK_RETURN && game_state == ST_TITLE) {
                    reset_level(); game_state = ST_PLAY; state_time = 0;
                }
                if (k == SDLK_r && (game_state == ST_CAUGHT || game_state == ST_WIN)) {
                    reset_level(); game_state = ST_PLAY; state_time = 0;
                }
            }
            if (e.type == SDL_MOUSEMOTION && game_state == ST_PLAY)
                rotate(e.motion.xrel * 0.0025);
        }

        if (game_state == ST_PLAY) {
            const Uint8 *ks = SDL_GetKeyboardState(NULL);
            double spd = (ks[SDL_SCANCODE_LSHIFT] ? PLAYER_RUN : PLAYER_WALK) * dt;
            int moving = 0;
            double nx = posX, ny = posY;
            if (ks[SDL_SCANCODE_W]) { nx += dirX * spd; ny += dirY * spd; moving = 1; }
            if (ks[SDL_SCANCODE_S]) { nx -= dirX * spd; ny -= dirY * spd; moving = 1; }
            if (ks[SDL_SCANCODE_D]) { nx += planeX * spd; ny += planeY * spd; moving = 1; }
            if (ks[SDL_SCANCODE_A]) { nx -= planeX * spd; ny -= planeY * spd; moving = 1; }
            if (ks[SDL_SCANCODE_LEFT])  rotate(-1.8 * dt);
            if (ks[SDL_SCANCODE_RIGHT]) rotate( 1.8 * dt);
            if (moving) try_move(nx, ny, 0.15);

            recalc -= dt;
            if (recalc <= 0) { flood_from_player(); recalc = 0.22; }
            update_monster(dt);

            /* flashlight flicker, heavier when the Stalker is near */
            flicker = 1.0 - (frand() < 0.04 + tension * 0.15 ? frand() * (0.4 + tension * 0.4) : 0);

            /* pick up keys */
            for (int i = 0; i < NUM_KEYS; i++)
                if (keys[i].active) {
                    double kd = (posX - keys[i].x) * (posX - keys[i].x) +
                                (posY - keys[i].y) * (posY - keys[i].y);
                    if (kd < PICKUP_DIST * PICKUP_DIST) {
                        keys[i].active = 0; keys_left--;
                        if (snd_pickup) Mix_PlayChannel(3, snd_pickup, 0);
                    }
                }
            /* reach the exit once the maze is unlocked */
            if (keys_left == 0) {
                double ed = (posX - exitX) * (posX - exitX) + (posY - exitY) * (posY - exitY);
                if (ed < 0.5) { game_state = ST_WIN; state_time = 0; }
            }
            /* caught */
            double md = sqrt((posX - monX) * (posX - monX) + (posY - monY) * (posY - monY));
            if (md < CATCH_DIST) {
                game_state = ST_CAUGHT; state_time = 0;
                if (snd_scare) { Mix_VolumeChunk(snd_scare, 128); Mix_PlayChannel(4, snd_scare, 0); }
            }
            update_audio(dt, moving);
        } else {
            update_audio(dt, 0);
        }

        /* ---- draw ---- */
        if (game_state == ST_TITLE) {
            draw_title();
        } else if (game_state == ST_CAUGHT) {
            draw_jumpscare();
        } else {
            render_world();
            render_sprites();
            draw_vignette();
            if (game_state == ST_WIN) draw_win();
            else draw_hud();
        }

        SDL_UpdateTexture(screen, NULL, fb, SCREEN_W * sizeof(uint32_t));
        SDL_RenderCopy(ren, screen, NULL, NULL);
        SDL_RenderPresent(ren);
    }

    if (snd_ambient) Mix_FreeChunk(snd_ambient);
    if (snd_heart)   Mix_FreeChunk(snd_heart);
    if (snd_scare)   Mix_FreeChunk(snd_scare);
    if (snd_pickup)  Mix_FreeChunk(snd_pickup);
    if (snd_step)    Mix_FreeChunk(snd_step);
    Mix_CloseAudio();
    SDL_DestroyTexture(screen);
    SDL_DestroyRenderer(ren);
    SDL_DestroyWindow(win);
    SDL_Quit();
    return 0;
}
